import Head from "next/head";
export default function ({ title }: { title?: string }) {
  title = title ?? "Bug tracker";
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.svg" />
    </Head>
  );
}
